// <auto-generated />
namespace ADO.NetExam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FlatFixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FlatFixed));
        
        string IMigrationMetadata.Id
        {
            get { return "202403291958579_FlatFixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
